### ISSUE TITLE
Cannot complete installation with docker-compose

### ISSUE THREAD

**Issue by esteinborn** [vladk1m0/docker-owa#1]
Hi, trying this out as a replacement to PIWIK, but running into an issue when running the install.

After running `docker-compose up` I get to the setup screen, and enter in the DB credentials properly.

But then the MYSQL server starts throwing these errors:

```
open-web-analytics | 2018/07/05 13:00:45 [error] 14#14: *1 FastCGI sent in stderr: "pers in /var/www/html/plugins/db/owa_db_mysql.php on line 112
open-web-analytics | PHP message: PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/plugins/db/owa_db_mysql.php on line 117
open-web-analytics | PHP message: PHP Warning:  mysqli_connect(): Server sent charset (255) unknown to the client. Please, report to the developers in /var/www/html/plugins/db/owa_db_mysql.php on line 112
open-web-analytics | PHP message: PHP Warning:  mysqli_connect(): (HY000/2054): Server sent charset unknown to the client. Please, report to the developers in /var/www/html/plugins/db/owa_db_mysql.php on line 112
open-web-analytics | PHP message: PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/plugins/db/owa_db_mysql.php on line 117
open-web-analytics | PHP message: PHP Warning:  mysqli_connect(): Server sent charset (255) unknown to the client. Please, report to the developers in /var/www/html/plugins/db/owa_db_mysql.php on line 112
open-web-analytics | PHP message: PHP Warning:  mysqli_connect(): (HY000/2054): Server sent charset unknown to the client. Please, report to the developers in /var/www/html/plugins/db/owa_db_mysql.php on line 112
open-web-analytics | PHP message: PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/plugins/db/owa_db_mysql.php on line 117
open-web-analytics | PHP message: PHP Warning:  mysqli_connect(): Server sent charset (255) unknown to the client. Please, report to the developers in /var/www/html/plugins/db/owa_db_mysql.php on line 112
open-web-analytics | PHP message: PHP Warning:  mysqli_connect(): (HY000/2054): Server sent charset unknown to the client. Please, report to the developers in /var/www/html/plugins/db/owa_db_mysql.php on line 112
open-web-analytics | PHP message: PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/plugins/db/owa_db_mysql.php on line 117
open-web-analytics | PHP message: PHP Warning:  mysqli_connect(): Server sent charset (255) unknown to the client. Please, report to the developers in /var/www/html/plugins/db/owa_db_mysql.php on line 11
```

any ideas?

Thanks

**Comment by cfsilence** [comment]
Same issue here.

**Comment by RBFUZ** [comment]
Same issue.

**Comment by vladk1m0** [comment]
Hi @RBFUZ @esteinborn @cfsilence ! Thanks for you feedback. Sorry for the long answer and my poor English. I fixed the issue by rollback a version of Mysql docker image to 5.7. To apply that patch, pull the changes from master branch. When you deploy OWA using docker-compose up then on OWA connection page to Mysql you need specify  following parameters:
db host = db
db name = owadb
db user = owauser
db password = password
Bootstrapping parameters for Mysql with docker-compose are defined in .env file.
Patches that fixed this issue for Mysql version 8 a welcomed.

**Comment by esteinborn** [comment]
*Slight correction*: default DB password is actually: `owapassword`

Confirmed that latest version of the `master` branch on GitHub works as expected now.

Thanks very much. 

P.S. Your English is not poor.

**Comment by RBFUZ** [comment]
Hi, thanks for fixing that ! 

Bye. 


De: "Eric Steinborn" <notifications@github.com> 
À: "vladk1m0/docker-owa" <docker-owa@noreply.github.com> 
Cc: "Remy Bouteloup" <remy.bouteloup@etu.univ-tours.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Lundi 6 Août 2018 15:57:07 
Objet: Re: [vladk1m0/docker-owa] Cannot complete installation with docker-compose (#1) 



Slight correction : default DB password is actually: owapassword 

Confirmed that latest version of the master branch on GitHub works as expected now. 

Thanks very much. 

P.S. Your English is not poor.

**Comment by vladk1m0** [comment]
@esteinborn, @RBFUZ, thank you very much for your help!
